# Assignment

1. Read regression_training.csv and extract Hours_Study (X) and Marks (Y).<br>
2. Calculate slope m and intercept b using the linear regression formulas.<br>
3. Predict Marks for the regression_test.csv values of Hours_Study.<br>
4. Print the regression equation and predicted results.<br>

In [105]:
import pandas as pd
import numpy as np

In [121]:
df = pd.read_csv("regression_training.csv")
df.head()

Hours_Study  Hours_Sleep  Extra_Classes  Marks
0            1            6              0     32
1            2            5              0     35
2            2            6              1     42
3            3            5              0     40
4            3            7              1     48

In [122]:
y = df['Marks'].to_numpy()
y
df['Marks'] = 1
x = df.to_numpy()
x

array([[ 1,  6,  0,  1],
       [ 2,  5,  0,  1],
       [ 2,  6,  1,  1],
       [ 3,  5,  0,  1],
       [ 3,  7,  1,  1],
       [ 4,  6,  0,  1],
       [ 4,  7,  1,  1],
       [ 5,  5,  0,  1],
       [ 5,  6,  1,  1],
       [ 6,  7,  0,  1],
       [ 6,  6,  1,  1],
       [ 7,  5,  0,  1],
       [ 7,  6,  1,  1],
       [ 8,  7,  0,  1],
       [ 8,  6,  1,  1],
       [ 9,  5,  0,  1],
       [ 9,  7,  1,  1],
       [10,  6,  0,  1],
       [10,  7,  1,  1],
       [11,  6,  1,  1]])

In [123]:
coefficients_1 = np.linalg.inv(np.matmul(x.T,x))
coefficients_2 = np.matmul(x.T,y)
coefficients = np.matmul(coefficients_1,coefficients_2)
coefficients

array([ 4.86616025,  2.12967987,  4.94306385, 14.89694339])

In [125]:
coefficients[0:3]
coefficients[3]

np.float64(14.896943389401258)

In [126]:
dft = pd.read_csv("regression_test.csv")
dft = dft.drop('Marks', axis=1)
dft

Hours_Study  Hours_Sleep  Extra_Classes
0            3            6              0
1            6            7              1
2            8            5              0
3           11            7              1

In [127]:
xt = dft.to_numpy()
xt

array([[ 3,  6,  0],
       [ 6,  7,  1],
       [ 8,  5,  0],
       [11,  7,  1]])

In [131]:
y = np.matmul(xt,coefficients[0:3])
y

array([27.37655996, 49.04778441, 49.57768132, 73.37858564])

In [132]:
output = y + coefficients[3]
output

array([42.27350335, 63.9447278 , 64.47462471, 88.27552903])

In [133]:
dft['Marks'] = output
dft

Hours_Study  Hours_Sleep  Extra_Classes      Marks
0            3            6              0  42.273503
1            6            7              1  63.944728
2            8            5              0  64.474625
3           11            7              1  88.275529

In [139]:
dft.to_csv("Regression_tested.csv",index=False)